---
services:
  postgres:
    image: postgres:16-alpine
    # restart: always
    restart: unless-stopped
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: test_db
    ports:
      - "5434:5432"
    networks:
      - test-app-net

networks:
  test-app-net:
    driver: bridge
